package teammates.storage.api;

import java.io.UnsupportedEncodingException;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.servlet.http.HttpServlet;
@SuppressWarnings("serial")
public class enviaralerta extends HttpServlet{
    public void enviar_Alerta(String destinatario,String instructorName,String evaluationName,String curseName,String timeStart,String timeEnd, int gracePeriod) throws UnsupportedEncodingException
    {
        String extraTime = Integer.toString(gracePeriod);
        
        Properties props = new Properties();
        Session session = Session.getDefaultInstance(props, null);

        String msgBody = " Hi "+ instructorName +",<br><br>Teammates' team here!<br>We remind you some evaluation where you are, just finished, this evaluation has the following data:<br><br>Evaluation's name: "+ evaluationName +"<br>Course: "+ curseName +"<br>Time start: " + timeStart + "<br>Time end: " + timeEnd+"<br>Extra time: " + extraTime + " mins<br><br>*This information is only for you and the instructors who are in the course, this message is only an alert.<br><br>Thank you very much for your time and have a nice day!<br>";
        System.out.println(msgBody);
        try {
            Message msg = new MimeMessage(session);
            msg.setFrom(new InternetAddress("pruebais2-1147@appspot.gserviceaccount.com")); 
            msg.addRecipient(Message.RecipientType.TO,
                                            new InternetAddress(destinatario));
            msg.setSubject("Evaluation Clousing Alert");
            msg.setContent(Formato(msgBody), "text/html");
            Transport.send(msg);

        } catch (AddressException e) {
            System.out.println("Error de dirección de correo");
        } catch (MessagingException e) {
            System.out.println("Error al enviar mensaje");
        }
    }
    
    public String Formato(String msgBody)
    {
        String msg2="<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html><head><title></title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /><link rel=\"stylesheet\" href=\"http://arequipagamers.netne.net/index.css\">"
                    + "<meta name=\"robots\" content=\"noindex,nofollow\" /><meta property=\"og:title\" content=\"My First Campaign\" /></head><!--[if mso]>  <body class=\"mso\"><![endif]--><!--[if !mso]><!--> <body class=\"full-padding\" style=\"margin: 0;padding: 0;min-width: 100%;background-color: #c5cbd1;\">"
                    + "<!--<![endif]--><center class=\"wrapper\" style=\"display: table;table-layout: fixed;width: 100%;min-width: 620px;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;background-color: #c5cbd1;\"><table class=\"preheader\" style=\"border-collapse: collapse;border-spacing: 0;font-size: 11px;line-height: 17px;width: 100%;\"> <tbody><tr>          <td class=\"title\" style=\"padding: 9px;vertical-align: top;font-family: Avenir,sans-serif;color: #606b75;text-align: left;width: 50%;background-color: #bac0c6;\"></td>"       
                    + "</tr></tbody></table><table class=\"header\" style=\"border-collapse: collapse;border-spacing: 0;width: 100%;\" align=\"center\"><tbody><tr>       <td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>         <td class=\"logo emb-logo-padding-box\" style=\"padding: 0;vertical-align: top;mso-line-height-rule: at-least;width: 600px;padding-top: 32px;padding-bottom: 20px;\">      <div class=\"logo-center\" style='font-weight: 400;font-family: \"PT Sans\",\"Trebuchet MS\",sans-serif;color: #606b75;text-align: center;font-size: 0px !important;line-height: 0 !important;' align=\"center\" id=\"emb-email-header\"><img style=\"border: 0;-ms-interpolation-mode: bicubic;display: block;Margin-left: auto;Margin-right: auto;max-width: 328px;\" src=\"http://arequipagamers.netne.net/logo21.png\" alt=\"\"  /></div> </td>"
                    + "<td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>  </tr>      </tbody></table>        <table class=\"one-col-bg\" style=\"border-collapse: collapse;border-spacing: 0;width: 100%;\">          <tbody><tr>             <td style=\"padding: 0;vertical-align: top;\" align=\"center\">              <table class=\"one-col centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;table-layout: fixed;\" emb-background-style>                <tbody><tr>                    <td class=\"column\" style=\"padding: 0;vertical-align: top;text-align: left;\">                  <div><div class=\"column-top\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div></div>                        <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;\">"
                    + "     <tbody><tr>                            <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;\">"
                    + "          <h2 style=\"font-style: normal;font-weight: 500;Margin-bottom: 0;Margin-top: 0;font-size: 24px;line-height: 32px;font-family: Avenir,sans-serif;color: #44596b;text-align: center;\">&nbsp;</h2><blockquote style=\"font-style: italic;font-weight: 400;Margin-left: 0;Margin-right: 0;padding-right: 0;Margin-bottom: 25px;Margin-top: 12px;border-left: 5px solid #aeb5bc;padding-left: 16px;\"><p style=\"font-style: normal;font-weight: 400;Margin-bottom: 25px;Margin-top: 0;font-size: 16px;line-height: 25px;font-family: Avenir,sans-serif;color: #8e8e8e;\">"
                    + msgBody
                    + "</p></blockquote>                 </td>                         </tr>                        </tbody></table>                <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;\">                          <tbody><tr>                            <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;\">"
                    + "<div class=\"btn btn--center\" style=\"Margin-bottom: 0;Margin-top: 0;text-align: center;\"><![if !mso]><a style=\"border-radius: 3px;display: inline-block;font-size: 14px;font-weight: 700;line-height: 24px;padding: 13px 35px 12px 35px;text-align: center;text-decoration: none !important;transition: opacity 0.2s ease-in;font-family: Avenir,sans-serif;background-color: #386994;color: #fff;\" href=\"http://google.com\">GO TO EVALUATION</a><![endif]><!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" href=\"http://google.com\" style=\"width:208px\" arcsize=\"7%\" fillcolor=\"#386994\" stroke=\"f\"><v:textbox style=\"mso-fit-shape-to-text:t\" inset=\"0px,12px,0px,11px\"><center style=\"font-size:14px;line-height:24px;color:#FFFFFF;font-family:sans-serif;font-weight:700;mso-line-height-rule:exactly;mso-text-raise:4px\">GO TO EVALUATION</center></v:textbox></v:roundrect><![endif]--></div></td></tr></tbody></table>  <div class=\"column-bottom\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div></td>"
                    + " </tr></tbody></table></td></tr></tbody></table><table class=\"one-col-bg\" style=\"border-collapse: collapse;border-spacing: 0;width: 100%;\"> <tbody><tr> <td style=\"padding: 0;vertical-align: top;\" align=\"center\">     <table class=\"one-col centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;table-layout: fixed;\" emb-background-style>   <tbody><tr>      <td class=\"column\" style=\"padding: 0;vertical-align: top;text-align: left;\">   <div><div class=\"column-top\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div></div><table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;\"> <tbody><tr> <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;\">  <h2 style=\"font-style: normal;font-weight: 500;Margin-bottom: 0;Margin-top: 0;font-size: 24px;line-height: 32px;font-family: Avenir,sans-serif;color: #44596b;text-align: center;\">&nbsp;</h2><blockquote style=\"font-style: italic;font-weight: 400;Margin-left: 0;Margin-right: 0;padding-right: 0;Margin-bottom: 0;Margin-top: 12px;border-left: 5px solid #aeb5bc;padding-left: 16px;\"><p style=\"font-style: normal;font-weight: 400;Margin-bottom: 0;Margin-top: 0;font-size: 16px;line-height: 25px;font-family: Avenir,sans-serif;color: #8e8e8e;\">Si no se visualiza ingrese a este link</p></blockquote>"
                    + "</td></tr>  </tbody></table><div class=\"column-bottom\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div>   </td>  </tr>  </tbody></table>    </td>   </tr>  </tbody></table><div class=\"spacer\" style=\"font-size: 1px;line-height: 34px;width: 100%;\">&nbsp;</div>    <table class=\"footer centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 100%;\"> <tbody><tr> <td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>   <td class=\"inner\" style=\"padding: 58px 0 29px 0;vertical-align: top;width: 600px;\">     <table class=\"right\" style=\"border-collapse: collapse;border-spacing: 0;\" align=\"right\">  <tbody><tr>                <td style=\"padding: 0;vertical-align: top;color: #606b75;font-size: 12px;line-height: 22px;max-width: 200px;mso-line-height-rule: at-least;\">  <div class=\"sharing\"></div>         </td>              </tr>         </tbody></table>            <table class=\"left\" style=\"border-collapse: collapse;border-spacing: 0;\" align=\"left\">              <tbody><tr>                <td style=\"padding: 0;vertical-align: top;color: #606b75;font-size: 12px;line-height: 22px;text-align: left;width: 400px;\">        <div class=\"address\" style=\"font-family: Avenir,sans-serif;Margin-bottom: 18px;\">           <div>S.A.&nbsp;Teammate Scrums&nbsp;</div>          </div>     <div class=\"permission\" style=\"font-family: Avenir,sans-serif;\">   <div>El presente mensaje fue enviado ya que esta suscrito a<br />teammate-scrums.appspot.com &nbsp;</div>                  </div>                  <div class=\"campaign\" style=\"font-family: Avenir,sans-serif;Margin-bottom: 18px;\">"
                    + " <unsubscribe>Unsubscribe</unsubscribe>  </div> </td>  </tr>   </tbody></table>   </td>          <td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>     </tr> </tbody></table> </center></body></html>";

        return msg2;
    }
    
    public String Formato2(String msgBody)
    {
        String msg2="<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html><head><title></title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /><link rel=\"stylesheet\" href=\"http://arequipagamers.netne.net/index.css\">"
                    + "<meta name=\"robots\" content=\"noindex,nofollow\" /><meta property=\"og:title\" content=\"My First Campaign\" /></head><!--[if mso]>  <body class=\"mso\"><![endif]--><!--[if !mso]><!--> <body class=\"full-padding\" style=\"margin: 0;padding: 0;min-width: 100%;background-color: #c5cbd1;\">"
                    + "<!--<![endif]--><center class=\"wrapper\" style=\"display: table;table-layout: fixed;width: 100%;min-width: 620px;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;background-color: #c5cbd1;\"><table class=\"preheader\" style=\"border-collapse: collapse;border-spacing: 0;font-size: 11px;line-height: 17px;width: 100%;\"> <tbody><tr>          <td class=\"title\" style=\"padding: 9px;vertical-align: top;font-family: Avenir,sans-serif;color: #606b75;text-align: left;width: 50%;background-color: #bac0c6;\"></td>"       
                    + "</tr></tbody></table><table class=\"header\" style=\"border-collapse: collapse;border-spacing: 0;width: 100%;\" align=\"center\"><tbody><tr>       <td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>         <td class=\"logo emb-logo-padding-box\" style=\"padding: 0;vertical-align: top;mso-line-height-rule: at-least;width: 600px;padding-top: 32px;padding-bottom: 20px;\">      <div class=\"logo-center\" style='font-weight: 400;font-family: \"PT Sans\",\"Trebuchet MS\",sans-serif;color: #606b75;text-align: center;font-size: 0px !important;line-height: 0 !important;' align=\"center\" id=\"emb-email-header\"><img style=\"border: 0;-ms-interpolation-mode: bicubic;display: block;Margin-left: auto;Margin-right: auto;max-width: 328px;\" src=\"http://arequipagamers.netne.net/logo21.png\" alt=\"\"  /></div> </td>"
                    + "<td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>  </tr>      </tbody></table>        <table class=\"one-col-bg\" style=\"border-collapse: collapse;border-spacing: 0;width: 100%;\">          <tbody><tr>             <td style=\"padding: 0;vertical-align: top;\" align=\"center\">              <table class=\"one-col centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;table-layout: fixed;\" emb-background-style>                <tbody><tr>                    <td class=\"column\" style=\"padding: 0;vertical-align: top;text-align: left;\">                  <div><div class=\"column-top\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div></div>                        <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;\">"
                    + "     <tbody><tr>                            <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;\">"
                    + "          <h2 style=\"font-style: normal;font-weight: 500;Margin-bottom: 0;Margin-top: 0;font-size: 24px;line-height: 32px;font-family: Avenir,sans-serif;color: #44596b;text-align: center;\">&nbsp;</h2><blockquote style=\"font-style: italic;font-weight: 400;Margin-left: 0;Margin-right: 0;padding-right: 0;Margin-bottom: 25px;Margin-top: 12px;border-left: 5px solid #aeb5bc;padding-left: 16px;\"><p style=\"font-style: normal;font-weight: 400;Margin-bottom: 25px;Margin-top: 0;font-size: 16px;line-height: 25px;font-family: Avenir,sans-serif;color: #8e8e8e;\">"
                    + msgBody
                    + "</p></blockquote>                 </td>                         </tr>                        </tbody></table>                <table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;\">                          <tbody><tr>                            <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;\">"
                    + "<div class=\"btn btn--center\" style=\"Margin-bottom: 0;Margin-top: 0;text-align: center;\"><![if !mso]><a style=\"border-radius: 3px;display: inline-block;font-size: 14px;font-weight: 700;line-height: 24px;padding: 13px 35px 12px 35px;text-align: center;text-decoration: none !important;transition: opacity 0.2s ease-in;font-family: Avenir,sans-serif;background-color: #386994;color: #fff;\" href=\"http://prueba-tablin.appspot.com\">GO TO TEAMMATES</a><![endif]><!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" href=\"http://google.com\" style=\"width:208px\" arcsize=\"7%\" fillcolor=\"#386994\" stroke=\"f\"><v:textbox style=\"mso-fit-shape-to-text:t\" inset=\"0px,12px,0px,11px\"><center style=\"font-size:14px;line-height:24px;color:#FFFFFF;font-family:sans-serif;font-weight:700;mso-line-height-rule:exactly;mso-text-raise:4px\">GO TO EVALUATION</center></v:textbox></v:roundrect><![endif]--></div></td></tr></tbody></table>  <div class=\"column-bottom\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div></td>"
                    + " </tr></tbody></table></td></tr></tbody></table><table class=\"one-col-bg\" style=\"border-collapse: collapse;border-spacing: 0;width: 100%;\"> <tbody><tr> <td style=\"padding: 0;vertical-align: top;\" align=\"center\">     <table class=\"one-col centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;table-layout: fixed;\" emb-background-style>   <tbody><tr>      <td class=\"column\" style=\"padding: 0;vertical-align: top;text-align: left;\">   <div><div class=\"column-top\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div></div><table class=\"contents\" style=\"border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;\"> <tbody><tr> <td class=\"padded\" style=\"padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;\">  <h2 style=\"font-style: normal;font-weight: 500;Margin-bottom: 0;Margin-top: 0;font-size: 24px;line-height: 32px;font-family: Avenir,sans-serif;color: #44596b;text-align: center;\">&nbsp;</h2><blockquote style=\"font-style: italic;font-weight: 400;Margin-left: 0;Margin-right: 0;padding-right: 0;Margin-bottom: 0;Margin-top: 12px;border-left: 5px solid #aeb5bc;padding-left: 16px;\"><p style=\"font-style: normal;font-weight: 400;Margin-bottom: 0;Margin-top: 0;font-size: 16px;line-height: 25px;font-family: Avenir,sans-serif;color: #8e8e8e;\">Si no se visualiza ingrese a este link</p></blockquote>"
                    + "</td></tr>  </tbody></table><div class=\"column-bottom\" style=\"font-size: 34px;line-height: 34px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;\">&nbsp;</div>   </td>  </tr>  </tbody></table>    </td>   </tr>  </tbody></table><div class=\"spacer\" style=\"font-size: 1px;line-height: 34px;width: 100%;\">&nbsp;</div>    <table class=\"footer centered\" style=\"border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 100%;\"> <tbody><tr> <td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>   <td class=\"inner\" style=\"padding: 58px 0 29px 0;vertical-align: top;width: 600px;\">     <table class=\"right\" style=\"border-collapse: collapse;border-spacing: 0;\" align=\"right\">  <tbody><tr>                <td style=\"padding: 0;vertical-align: top;color: #606b75;font-size: 12px;line-height: 22px;max-width: 200px;mso-line-height-rule: at-least;\">  <div class=\"sharing\"></div>         </td>              </tr>         </tbody></table>            <table class=\"left\" style=\"border-collapse: collapse;border-spacing: 0;\" align=\"left\">              <tbody><tr>                <td style=\"padding: 0;vertical-align: top;color: #606b75;font-size: 12px;line-height: 22px;text-align: left;width: 400px;\">        <div class=\"address\" style=\"font-family: Avenir,sans-serif;Margin-bottom: 18px;\">           <div>S.A.&nbsp;Teammate Scrums&nbsp;</div>          </div>     <div class=\"permission\" style=\"font-family: Avenir,sans-serif;\">   <div>El presente mensaje fue enviado ya que esta suscrito a<br />teammate-scrums.appspot.com &nbsp;</div>                  </div>                  <div class=\"campaign\" style=\"font-family: Avenir,sans-serif;Margin-bottom: 18px;\">"
                    + " <unsubscribe>Unsubscribe</unsubscribe>  </div> </td>  </tr>   </tbody></table>   </td>          <td style=\"padding: 0;vertical-align: top;\">&nbsp;</td>     </tr> </tbody></table> </center></body></html>";

        return msg2;
    }
    
}

 